3.1

In [1]:
import numpy as np

print("Phiên bản NumPy hiện tại:", np.__version__)
print("Cấu hình xây dựng NumPy:")
np.show_config()


Phiên bản NumPy hiện tại: 2.3.3
Cấu hình xây dựng NumPy:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5t0hy_xh/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5t0hy_xh/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5t0hy_xh/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5t0hy_xh/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib

3.2.1

In [2]:
arr = np.arange(10)

print("arr =", arr)
print("Kiểu dữ liệu:", arr.dtype)
print("Kích thước:", arr.shape)


arr = [0 1 2 3 4 5 6 7 8 9]
Kiểu dữ liệu: int64
Kích thước: (10,)


3.2.2

In [3]:
arr_even = arr[arr % 2 == 0]
arr_odd = arr[arr % 2 != 0]

print("arr_even =", arr_even)
print("arr_odd =", arr_odd)


arr_even = [0 2 4 6 8]
arr_odd = [1 3 5 7 9]


3.2.3

In [4]:
arr_update = arr.copy()
arr_update[arr_update % 2 != 0] = 100

print("arr_update =", arr_update)


arr_update = [  0 100   2 100   4 100   6 100   8 100]


3.3

In [5]:
arr_a = np.array([1,2,3,2,3,4,3,4,5,6])
arr_b = np.array([7,2,10,2,7,4,9,4,9,8])


In [6]:
arr_c = np.intersect1d(arr_a, arr_b)

print("arr_c =", arr_c)


arr_c = [2 4]


In [7]:
arr_d = np.setdiff1d(arr_a, arr_b)

print("arr_d =", arr_d)


arr_d = [1 3 5 6]


In [8]:
arr_e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 16])

arr_f = arr_e[(arr_e >= 5) & (arr_e <= 10)]

print("arr_f =", arr_f)


arr_f = [ 6  9 10  8  6]


3.4

In [9]:
arr_zeros = np.zeros(10, dtype=int)
arr_zeros[4] = 1

print("arr_zeros =", arr_zeros)


arr_zeros = [0 0 0 0 1 0 0 0 0 0]


In [10]:
arr_h = np.arange(10, 25)

print("arr_h đảo ngược =", arr_h[::-1])


arr_h đảo ngược = [24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [11]:
arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])

arr_l = arr_k[arr_k != 0]

print("arr_l =", arr_l)


arr_l = [1 2 8 2 1 3 5]


In [12]:
arr_l = np.append(arr_l, [10, 20])

print("arr_l sau khi thêm =", arr_l)


arr_l sau khi thêm = [ 1  2  8  2  1  3  5 10 20]


In [13]:
arr_m = np.insert(arr_l, 5, 100)

print("arr_m =", arr_m)


arr_m = [  1   2   8   2   1 100   3   5  10  20]


In [14]:
arr_n = np.delete(arr_m, [0, 1, 2])

print("arr_n =", arr_n)


arr_n = [  2   1 100   3   5  10  20]


3.5

In [15]:
import numpy as np
arr_height = np.random.randint(60, 80, 200)   # giả sử inch
arr_height_m = arr_height * 0.0254

arr_height_m


array([1.7272, 1.9812, 1.524 , 1.8796, 1.8034, 1.8288, 1.7272, 1.5494,
       1.5748, 1.6256, 1.7272, 1.7272, 1.7272, 1.8542, 1.524 , 1.6764,
       1.651 , 1.6764, 1.6764, 1.7018, 1.5494, 1.8034, 1.7018, 1.8288,
       1.8542, 1.7526, 1.778 , 1.7272, 1.8288, 1.905 , 1.9558, 1.5748,
       1.651 , 1.8796, 2.0066, 1.5494, 1.8288, 1.8796, 1.7526, 1.778 ,
       1.8542, 1.8796, 1.8542, 1.7018, 1.7272, 1.8288, 1.7526, 1.778 ,
       1.905 , 1.524 , 1.6256, 1.7018, 1.8542, 1.7526, 1.8288, 1.8796,
       1.8288, 1.8288, 1.8288, 1.7272, 1.9812, 1.8034, 1.6764, 1.8288,
       1.905 , 1.5494, 1.7272, 1.9304, 1.9304, 1.524 , 1.5748, 1.778 ,
       1.5494, 1.8542, 1.9812, 1.5748, 2.0066, 1.778 , 1.6764, 1.9812,
       1.905 , 1.7272, 1.5494, 1.5494, 1.5748, 1.8288, 1.7526, 1.524 ,
       1.7526, 2.0066, 1.5748, 1.9812, 2.0066, 1.524 , 1.7018, 2.0066,
       1.9558, 2.0066, 1.7526, 1.905 , 1.524 , 1.524 , 1.7018, 2.0066,
       1.8288, 1.8034, 2.0066, 1.651 , 1.8288, 1.524 , 1.6256, 1.7526,
      

In [16]:
arr_weight = np.random.randint(120, 220, 200)   # giả sử pound
arr_weight_kg = arr_weight * 0.453592

arr_weight_kg


array([67.585208, 70.760352, 61.688512, 97.975872, 58.513368, 78.017824,
       81.192968, 55.791816, 99.336648, 73.028312, 70.760352, 97.975872,
       93.893544, 58.059776, 73.935496, 85.728888, 75.296272, 56.699   ,
       66.224432, 64.863656, 61.688512, 84.821704, 75.749864, 64.410064,
       69.853168, 58.513368, 87.996848, 74.389088, 72.121128, 78.925008,
       62.595696, 86.636072, 96.161504, 85.728888, 55.791816, 67.131616,
       95.25432 , 64.863656, 54.884632, 68.0388  , 94.347136, 70.760352,
       97.068688, 85.728888, 59.420552, 93.893544, 93.439952, 60.781328,
       95.25432 , 91.171992, 93.439952, 98.883056, 60.327736, 70.760352,
       97.068688, 77.11064 , 69.853168, 94.347136, 86.636072, 75.296272,
       92.532768, 95.707912, 92.532768, 76.203456, 97.068688, 91.625584,
       61.23492 , 95.707912, 80.285784, 59.874144, 86.18248 , 62.595696,
       83.91452 , 69.399576, 83.460928, 64.863656, 91.625584, 54.884632,
       95.707912, 97.52228 , 86.636072, 84.368112, 

In [17]:
arr_bmi = arr_weight_kg / (arr_height_m ** 2)

arr_bmi


array([22.65512152, 18.02741041, 26.56038468, 27.73245167, 17.99164884,
       23.32713523, 27.21655538, 23.24038908, 40.05518011, 27.63528076,
       23.71945609, 32.84232382, 31.47389366, 16.88737714, 31.83340222,
       30.50506018, 27.62353965, 20.17530435, 23.56475549, 22.39671817,
       25.69669036, 26.08091731, 26.15560794, 19.25844886, 20.31762562,
       19.04975883, 27.8357933 , 24.93583845, 21.5640378 , 21.74826792,
       16.36423054, 34.93396987, 35.27825546, 24.26589521, 13.85635119,
       27.96404539, 28.48080465, 18.35991013, 17.86837844, 21.5225206 ,
       27.44198785, 20.02899287, 28.23358366, 29.60125689, 19.9182612 ,
       28.07393601, 30.42054511, 19.22678507, 26.24790956, 39.25468618,
       35.35942755, 34.14324868, 17.54704031, 23.03691766, 29.02329616,
       21.82646659, 20.88592341, 28.20955889, 25.90396994, 25.23993404,
       23.57430593, 29.42820081, 32.92609671, 22.78464372, 26.74786974,
       38.16714304, 20.52645239, 25.68344188, 21.54487779, 25.77

In [18]:
arr_weight_kg[50]


np.float64(93.439952)

In [19]:
arr_height_m_100 = arr_height_m[100:111]

arr_height_m_100


array([1.524 , 1.524 , 1.7018, 2.0066, 1.8288, 1.8034, 2.0066, 1.651 ,
       1.8288, 1.524 , 1.6256])

In [20]:
arr_bmi[arr_bmi < 21]


array([18.02741041, 17.99164884, 16.88737714, 20.17530435, 19.25844886,
       20.31762562, 19.04975883, 16.36423054, 13.85635119, 18.35991013,
       17.86837844, 20.02899287, 19.9182612 , 19.22678507, 17.54704031,
       20.88592341, 20.52645239, 19.80071895, 20.18569299, 17.36149995,
       18.85158022, 20.95350667, 15.20819033, 17.1943002 , 20.61554689,
       14.19431097, 15.99676316, 18.44471158, 17.72070589, 19.92182772,
       15.71620395, 17.46125556, 19.90060189, 17.1943002 , 19.24688015,
       16.49157924, 15.58047659, 16.04887249, 20.18569299, 20.33670679,
       13.74369792, 17.58956425, 18.58778818, 18.07477085, 20.67415687,
       19.3863503 , 16.81723703, 20.58149089, 18.70044144, 14.90728169,
       17.91185009, 18.3090887 , 19.51375201])

In [21]:
np.mean(arr_height_m), np.mean(arr_weight_kg)


(np.float64(1.7597119999999997), np.float64(76.63210043999999))

In [22]:
np.max(arr_height_m), np.max(arr_weight_kg)


(np.float64(2.0065999999999997), np.float64(99.336648))

In [23]:
np.min(arr_height_m), np.min(arr_weight_kg)


(np.float64(1.524), np.float64(54.431039999999996))

3.6

In [24]:
arr = np.ones((3, 3), dtype=bool)

arr


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [25]:
arr_1D = np.array([0,1,2,3,4,5,6,7,8])
arr_2D = arr_1D.reshape(3, 3)

arr_2D


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
arr_2D[[0, 1]] = arr_2D[[1, 0]]

arr_2D


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [27]:
arr_2D[::-1]


array([[6, 7, 8],
       [0, 1, 2],
       [3, 4, 5]])

In [28]:
arr_2D[:, ::-1]


array([[5, 4, 3],
       [2, 1, 0],
       [8, 7, 6]])

In [29]:
arr_2D_null = np.array([[1, 2, 3],
                        [np.nan, 5, 6],
                        [7, np.nan, 9],
                        [4, 5, 6]])

np.isnan(arr_2D_null)


array([[False, False, False],
       [ True, False, False],
       [False,  True, False],
       [False, False, False]])

In [30]:
arr_2D_null[np.isnan(arr_2D_null)] = 0

arr_2D_null


array([[1., 2., 3.],
       [0., 5., 6.],
       [7., 0., 9.],
       [4., 5., 6.]])

3.7

In [37]:
import numpy as np
import os

# Đọc dữ liệu từ file baseball_2D.txt (nếu có), nếu không thì dùng dữ liệu mẫu
if os.path.exists("baseball_2D.txt"):
    baseball = np.loadtxt("baseball_2D.txt").tolist()
else:
    baseball = [
        [180, 80],
        [175, 75],
        [190, 90],
        [185, 85],
        [178, 78]
    ]

# Tạo 2D numpy array np_baseball, kiểm tra kiểu dữ liệu và kích thước
np_baseball = np.array(baseball)
print("dtype:", np_baseball.dtype)
print("shape:", np_baseball.shape)

# In dòng thứ 50
if np_baseball.shape[0] >= 50:
    print("Dòng 50:", np_baseball[49])
else:
    print("Không đủ 50 dòng")

# Tạo numpy array np_weight từ cột cân nặng
np_weight = np_baseball[:, 1]
print("np_weight:", np_weight)

# Chiều cao và cân nặng của vận động viên thứ 124
if np_baseball.shape[0] >= 124:
    print("VĐV thứ 124:", np_baseball[123])
else:
    print("Không đủ 124 vận động viên")

# Chiều cao trung bình và cân nặng trung bình
print("Chiều cao TB:", np.mean(np_baseball[:, 0]))
print("Cân nặng TB:", np.mean(np_baseball[:, 1]))

# Mối tương quan chiều cao – cân nặng
print("Ma trận tương quan:")
print(np.corrcoef(np_baseball[:, 0], np_baseball[:, 1]))


dtype: int64
shape: (5, 2)
Không đủ 50 dòng
np_weight: [80 75 90 85 78]
Không đủ 124 vận động viên
Chiều cao TB: 181.6
Cân nặng TB: 81.6
Ma trận tương quan:
[[1. 1.]
 [1. 1.]]


3.8

In [38]:
# import thư viện
import numpy as np
import os

# đọc dữ liệu từ file, nếu không có thì dùng dữ liệu mẫu
if os.path.exists("positions.txt") and os.path.exists("heights.txt"):
    positions = np.loadtxt("positions.txt", dtype=str)
    heights = np.loadtxt("heights.txt")
else:
    positions = np.array(['GK','M','A','D','GK','M','D','A','GK','M'])
    heights = np.array([190, 175, 180, 185, 192, 178, 182, 176, 195, 170])

# Ý 1: tạo numpy array np_positions và kiểm tra kiểu dữ liệu
np_positions = np.array(positions)
print("np_positions dtype:", np_positions.dtype)

# Ý 2: tạo numpy array np_heights và kiểm tra kiểu dữ liệu
np_heights = np.array(heights)
print("np_heights dtype:", np_heights.dtype)

# Ý 3: tính chiều cao trung bình của các GK
print("Chiều cao TB GK:", np.mean(np_heights[np_positions == 'GK']))

# Ý 4: tính chiều cao trung bình của các vị trí khác GK
print("Chiều cao TB vị trí khác GK:", np.mean(np_heights[np_positions != 'GK']))

# Ý 5: tìm cầu thủ thấp nhất và cao nhất
idx_min = np.argmin(np_heights)
idx_max = np.argmax(np_heights)
print("Thấp nhất:", np_positions[idx_min], np_heights[idx_min])
print("Cao nhất:", np_positions[idx_max], np_heights[idx_max])


np_positions dtype: <U2
np_heights dtype: int64
Chiều cao TB GK: 192.33333333333334
Chiều cao TB vị trí khác GK: 178.0
Thấp nhất: M 170
Cao nhất: GK 195


3.9

In [ ]:
import numpy as np
from io import StringIO

# ===== DỮ LIỆU EURO 2012 
csv_data = """Team,Goals,Shooting Accuracy,Yellow Cards,Red Cards
Croatia,4,51.9,9,0
Czech Republic,4,41.3,7,0
Denmark,4,38.5,4,0
England,5,50.0,5,0
France,3,37.9,6,0
Germany,10,56.3,4,0
Greece,5,32.1,9,1
Italy,6,43.0,16,0
Netherlands,2,44.1,5,0
Poland,2,31.7,7,1
Portugal,6,41.5,12,0
Republic of Ireland,1,36.8,6,1
Russia,5,39.9,6,0
Spain,12,55.9,11,0
Sweden,5,47.2,7,0
Ukraine,2,21.2,5,0
"""

# ===== ĐỌC DỮ LIỆU =====
euro12 = np.genfromtxt(
    StringIO(csv_data),
    delimiter=",",
    names=True,
    dtype=None,
    encoding="utf-8"
)

# 1. In giá trị cột Goals
print("1. Goals:")
print(euro12["Goals"])

# 2. Có bao nhiêu đội tham gia Euro2012
print("\n2. Số đội tham gia:")
print(len(euro12))

# 3. Thông tin euro12
print("\n3. Thông tin euro12:")
print("Type:", type(euro12))
print("Shape:", euro12.shape)
print("Columns:", euro12.dtype.names)

# 4. Tạo euro12_discipline
euro12_discipline = euro12[["Team", "Yellow_Cards", "Red_Cards"]]
print("\n4. euro12_discipline:")
print(euro12_discipline)

# 5. Sắp xếp giảm dần theo Red Cards, Yellow Cards (ĐÚNG)
idx = np.lexsort((
    -euro12_discipline["Yellow_Cards"],  # khóa phụ
    -euro12_discipline["Red_Cards"]      # khóa chính
))
print("\n5. Sắp xếp discipline giảm dần:")
print(euro12_discipline[idx])

# 6a. Tính trung bình Yellow Cards (ĐÚNG)
print("\n6a. Trung bình Yellow Cards:")
print(np.mean(euro12["Yellow_Cards"]))

# 6b. Lọc các đội ghi hơn 6 bàn thắng (ĐÚNG)
print("\n6b. Các đội ghi hơn 6 bàn:")
print(euro12[euro12["Goals"] > 6]["Team"])

# 7. In các đội tên bắt đầu bằng 'G'
print("\n7. Đội bắt đầu bằng 'G':")
print(euro12[np.char.startswith(euro12["Team"], "G")]["Team"])

# 8. In 7 cột đầu (dataset này có 5 cột)
print("\n8. Các cột hiện có:")
print(euro12)

# 9. In tất cả các cột trừ 3 cột cuối
print("\n9. Tất cả cột trừ 3 cột cuối:")
print(euro12[["Team", "Goals"]])

# 10. In các cột Team, Goals, Shooting Accuracy, Yellow Cards, Red Cards
print("\n10. Các cột yêu cầu:")
print(euro12[["Team", "Goals", "Shooting_Accuracy", "Yellow_Cards", "Red_Cards"]])

# 11. Team & Shooting Accuracy của England, Italy, Russia
print("\n11. England, Italy, Russia:")
mask = np.isin(euro12["Team"], ["England", "Italy", "Russia"])
print(euro12[mask][["Team", "Shooting_Accuracy"]])


1. Goals:
[ 4  4  4  5  3 10  5  6  2  2  6  1  5 12  5  2]

2. Số đội tham gia:
16

3. Thông tin euro12:
Type: <class 'numpy.ndarray'>
Shape: (16,)
Columns: ('Team', 'Goals', 'Shooting_Accuracy', 'Yellow_Cards', 'Red_Cards')

4. euro12_discipline:
[('Croatia',  9, 0) ('Czech Republic',  7, 0) ('Denmark',  4, 0)
 ('England',  5, 0) ('France',  6, 0) ('Germany',  4, 0) ('Greece',  9, 1)
 ('Italy', 16, 0) ('Netherlands',  5, 0) ('Poland',  7, 1)
 ('Portugal', 12, 0) ('Republic of Ireland',  6, 1) ('Russia',  6, 0)
 ('Spain', 11, 0) ('Sweden',  7, 0) ('Ukraine',  5, 0)]

5. Sắp xếp discipline giảm dần:
[('Greece',  9, 1) ('Poland',  7, 1) ('Republic of Ireland',  6, 1)
 ('Italy', 16, 0) ('Portugal', 12, 0) ('Spain', 11, 0) ('Croatia',  9, 0)
 ('Czech Republic',  7, 0) ('Sweden',  7, 0) ('France',  6, 0)
 ('Russia',  6, 0) ('England',  5, 0) ('Netherlands',  5, 0)
 ('Ukraine',  5, 0) ('Denmark',  4, 0) ('Germany',  4, 0)]

6a. Trung bình Yellow Cards:
7.4375

6b. Các đội ghi hơn 6 bàn:
['G

3.10

In [44]:
import numpy as np
from io import StringIO

# ===== DỮ LIỆU drinks.csv 
csv_data = """country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
Afghanistan,0,0,0,0.0,Asia
Albania,89,132,54,4.9,Europe
Algeria,25,0,14,0.7,Africa
Andorra,245,138,312,12.4,Europe
Angola,217,57,45,5.9,Africa
Argentina,193,25,221,8.3,South America
Australia,261,72,212,10.4,Oceania
Austria,279,75,191,9.7,Europe
Bangladesh,0,0,0,0.0,Asia
Belgium,295,84,212,10.5,Europe
Brazil,245,145,16,7.2,South America
Canada,240,122,100,8.2,North America
China,79,192,8,5.0,Asia
Denmark,224,81,278,10.4,Europe
Egypt,6,4,1,0.1,Africa
Finland,263,133,97,10.0,Europe
France,127,151,370,11.8,Europe
Germany,346,117,175,11.3,Europe
Greece,133,112,218,8.3,Europe
India,9,114,0,2.2,Asia
Italy,85,42,237,6.5,Europe
Japan,77,202,16,7.0,Asia
Mexico,238,68,5,5.5,North America
Norway,169,71,129,6.7,Europe
Portugal,194,67,339,11.0,Europe
Russia,247,326,73,11.5,Europe
Spain,284,157,112,10.0,Europe
USA,249,158,84,8.7,North America
Vietnam,111,2,1,2.0,Asia
"""

# ===== ĐỌC DỮ LIỆU =====
drink = np.genfromtxt(
    StringIO(csv_data),
    delimiter=",",
    names=True,
    dtype=None,
    encoding="utf-8"
)

# 1. Thông tin dữ liệu
print("1. Thông tin drink:")
print("Type:", type(drink))
print("Shape:", drink.shape)
print("Columns:", drink.dtype.names)
print("\nHead (5 dòng đầu):")
print(drink[:5])
print("\nTail (5 dòng cuối):")
print(drink[-5:])

# ===== GROUP BY THEO CONTINENT =====
continents = np.unique(drink["continent"])

# 2. Số lượng bia tiêu thụ trung bình mỗi châu lục
print("\n2. Beer servings trung bình mỗi châu lục:")
for c in continents:
    print(c, ":", np.mean(drink["beer_servings"][drink["continent"] == c]))

# 3. Describe wine_servings theo châu lục
print("\n3. Thống kê wine_servings theo châu lục:")
for c in continents:
    data = drink["wine_servings"][drink["continent"] == c]
    print(c, ": min =", np.min(data),
          "max =", np.max(data),
          "mean =", np.mean(data),
          "std =", np.std(data))

# 4. Mean bia & rượu theo châu lục
print("\n4. Mean beer & wine theo châu lục:")
for c in continents:
    mask = drink["continent"] == c
    print(c,
          "Beer =", np.mean(drink["beer_servings"][mask]),
          "Wine =", np.mean(drink["wine_servings"][mask]))

# 5. Median bia & rượu theo châu lục
print("\n5. Median beer & wine theo châu lục:")
for c in continents:
    mask = drink["continent"] == c
    print(c,
          "Beer =", np.median(drink["beer_servings"][mask]),
          "Wine =", np.median(drink["wine_servings"][mask]))

# 6. Spirit_servings: mean, max, min mỗi châu lục
print("\n6. Spirit_servings theo châu lục:")
for c in continents:
    data = drink["spirit_servings"][drink["continent"] == c]
    print(c,
          "Mean =", np.mean(data),
          "Max =", np.max(data),
          "Min =", np.min(data))

# 7. Sắp xếp theo beer_servings tăng dần
sorted_drink = np.sort(drink, order="beer_servings")

print("\n7a. 5 quốc gia uống bia nhiều nhất:")
print(sorted_drink[-5:][["country", "beer_servings"]])

print("\n7b. 5 quốc gia uống bia ít nhất:")
print(sorted_drink[:5][["country", "beer_servings"]])


1. Thông tin drink:
Type: <class 'numpy.ndarray'>
Shape: (29,)
Columns: ('country', 'beer_servings', 'spirit_servings', 'wine_servings', 'total_litres_of_pure_alcohol', 'continent')

Head (5 dòng đầu):
[('Afghanistan',   0,   0,   0,  0. , 'Asia')
 ('Albania',  89, 132,  54,  4.9, 'Europe')
 ('Algeria',  25,   0,  14,  0.7, 'Africa')
 ('Andorra', 245, 138, 312, 12.4, 'Europe')
 ('Angola', 217,  57,  45,  5.9, 'Africa')]

Tail (5 dòng cuối):
[('Portugal', 194,  67, 339, 11. , 'Europe')
 ('Russia', 247, 326,  73, 11.5, 'Europe')
 ('Spain', 284, 157, 112, 10. , 'Europe')
 ('USA', 249, 158,  84,  8.7, 'North America')
 ('Vietnam', 111,   2,   1,  2. , 'Asia')]

2. Beer servings trung bình mỗi châu lục:
Africa : 82.66666666666667
Asia : 46.0
Europe : 212.85714285714286
North America : 242.33333333333334
Oceania : 261.0
South America : 219.0

3. Thống kê wine_servings theo châu lục:
Africa : min = 1 max = 45 mean = 20.0 std = 18.457157599876172
Asia : min = 0 max = 16 mean = 4.16666666666666

3.11

In [49]:
import pandas as pd
import numpy as np
from io import StringIO

# =========================
# DỮ LIỆU stocks1.csv
# =========================
stocks1_csv = """date,symbol,open,high,low,close,volume
2023-01-01,AAPL,130,135,128,134,10000
2023-01-02,AAPL,134,,132,133,12000
2023-01-01,MSFT,220,225,218,224,15000
2023-01-02,MSFT,224,226,,225,14000
"""

stocks1 = pd.read_csv(StringIO(stocks1_csv))

print("1a. stocks1 head:")
print(stocks1.head())
print("\n1a. stocks1 tail:")
print(stocks1.tail())
print("\nDtypes stocks1:")
print(stocks1.dtypes)
print("\nInfo stocks1:")
stocks1.info()

# =========================
# DỮ LIỆU stocks2.csv
# =========================
stocks2_csv = """date,symbol,open,high,low,close,volume
2023-01-03,AAPL,133,136,131,135,11000
2023-01-03,MSFT,225,228,223,227,16000
"""

stocks2 = pd.read_csv(StringIO(stocks2_csv))

print("\n1b. stocks2 head:")
print(stocks2.head())
print("\n1b. stocks2 tail:")
print(stocks2.tail())
print("\nDtypes stocks2:")
print(stocks2.dtypes)
print("\nInfo stocks2:")
stocks2.info()

# =========================
# DỮ LIỆU companies.csv
# =========================
companies_csv = """symbol,name,employees,headquarters_city,headquarters_state
AAPL,Apple,160000,Cupertino,CA
MSFT,Microsoft,221000,Redmond,WA
"""

companies = pd.read_csv(StringIO(companies_csv))

print("\n1c. companies:")
print(companies.head())
print("\nDtypes companies:")
print(companies.dtypes)
print("\nInfo companies:")
companies.info()

# =========================
# 2. Xử lý NULL trong stocks1
# =========================
stocks1["high"] = stocks1.groupby("symbol")["high"]\
    .transform(lambda x: x.fillna(x.max()))

stocks1["low"] = stocks1.groupby("symbol")["low"]\
    .transform(lambda x: x.fillna(x.min()))

# =========================
# 3. Gộp stocks1 & stocks2
# =========================
stocks = pd.concat([stocks1, stocks2], ignore_index=True)
print("\n3. 15 dòng cuối stocks:")
print(stocks.tail(15))

# =========================
# 4. Gộp stocks với companies
# =========================
stocks_companies = pd.merge(stocks, companies, on="symbol", how="left")
print("\n4. stocks_companies head:")
print(stocks_companies.head())

# =========================
# 5. Giá & volume trung bình mỗi công ty
# =========================
print("\n5. Mean open, high, low, close, volume:")
print(
    stocks_companies.groupby("symbol")[["open","high","low","close","volume"]]
    .mean()
)

# =========================
# 6. Close trung bình, max, min
# =========================
print("\n6. Close mean, max, min:")
print(
    stocks_companies.groupby("symbol")["close"]
    .agg(["mean","max","min"])
)

# =========================
# 7. parsed_time
# =========================
stocks_companies["parsed_time"] = pd.to_datetime(stocks_companies["date"])
print("\n7. parsed_time dtype:")
print(stocks_companies["parsed_time"].dtype)
print(stocks_companies[["parsed_time"]].head())

# =========================
# 8. result
# =========================
stocks_companies["result"] = np.where(
    stocks_companies["close"] > stocks_companies["open"],
    "up",
    "down"
)

print("\n8. result:")
print(stocks_companies[["open","close","result"]].head())


1a. stocks1 head:
         date symbol  open   high    low  close  volume
0  2023-01-01   AAPL   130  135.0  128.0    134   10000
1  2023-01-02   AAPL   134    NaN  132.0    133   12000
2  2023-01-01   MSFT   220  225.0  218.0    224   15000
3  2023-01-02   MSFT   224  226.0    NaN    225   14000

1a. stocks1 tail:
         date symbol  open   high    low  close  volume
0  2023-01-01   AAPL   130  135.0  128.0    134   10000
1  2023-01-02   AAPL   134    NaN  132.0    133   12000
2  2023-01-01   MSFT   220  225.0  218.0    224   15000
3  2023-01-02   MSFT   224  226.0    NaN    225   14000

Dtypes stocks1:
date       object
symbol     object
open        int64
high      float64
low       float64
close       int64
volume      int64
dtype: object

Info stocks1:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   date    4 non-null      object 
 1   symbol  4 non-n

3.12

In [50]:
import pandas as pd
import numpy as np
from io import StringIO

# =========================
# DỮ LIỆU movies.csv
# =========================
movies_csv = """movieId,title,genres
1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
2,Jumanji (1995),Adventure|Children|Fantasy
3,Grumpier Old Men (1995),Comedy|Romance
4,Waiting to Exhale (1995),Comedy|Drama
"""

movies = pd.read_csv(StringIO(movies_csv))

# =========================
# DỮ LIỆU ratings.csv
# =========================
ratings_csv = """userId,movieId,rating,timestamp
1,1,4.0,964982703
1,3,4.0,964981247
2,1,5.0,964982224
2,2,3.0,964983815
3,1,4.5,964982931
"""

ratings = pd.read_csv(StringIO(ratings_csv))

# =========================
# DỮ LIỆU users.csv
# =========================
users_csv = """userId,gender,age
1,M,25
2,F,30
3,M,35
"""

users = pd.read_csv(StringIO(users_csv))

# ==================================================
# 1. Đọc dữ liệu & Data Structures
# ==================================================
print("1. Movies info:")
movies.info()
print("\nRatings info:")
ratings.info()
print("\nUsers info:")
users.info()

# ==================================================
# 2. Xử lý dữ liệu thiếu / không hợp lệ
# ==================================================
print("\n2. Kiểm tra dữ liệu thiếu:")
print(movies.isnull().sum())
print(ratings.isnull().sum())
print(users.isnull().sum())

# (Dataset mẫu không có thiếu → nếu có thì xử lý bằng fillna)

# ==================================================
# 3. Gộp DataFrame (ratings + movies)
# ==================================================
movie_ratings = pd.merge(ratings, movies, on="movieId", how="left")
print("\n3. movie_ratings:")
print(movie_ratings.head())

# ==================================================
# 4. Gộp tiếp với users
# ==================================================
full_data = pd.merge(movie_ratings, users, on="userId", how="left")
print("\n4. full_data:")
print(full_data.head())

# ==================================================
# 5. Lọc dữ liệu theo yêu cầu
# Ví dụ: rating >= 4
# ==================================================
high_rating = full_data[full_data["rating"] >= 4]
print("\n5. Rating >= 4:")
print(high_rating)

# ==================================================
# 6. Thống kê dữ liệu
# Rating trung bình mỗi phim
# ==================================================
print("\n6. Rating trung bình mỗi phim:")
print(
    full_data.groupby("title")["rating"]
    .mean()
)

# ==================================================
# 7. Thống kê số lượt rating mỗi phim
# ==================================================
print("\n7. Số lượt rating mỗi phim:")
print(
    full_data.groupby("title")["rating"]
    .count()
)

# ==================================================
# 8. Parsing Timestamp
# ==================================================
full_data["rating_time"] = pd.to_datetime(full_data["timestamp"], unit="s")

print("\n8. Kiểu dữ liệu rating_time:")
print(full_data["rating_time"].dtype)

print("\n5 dòng đầu rating_time:")
print(full_data[["rating_time"]].head())


1. Movies info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   movieId  4 non-null      int64 
 1   title    4 non-null      object
 2   genres   4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

Ratings info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   userId     5 non-null      int64  
 1   movieId    5 non-null      int64  
 2   rating     5 non-null      float64
 3   timestamp  5 non-null      int64  
dtypes: float64(1), int64(3)
memory usage: 292.0 bytes

Users info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   userId  3 non-null      int64 
 1   gender  